apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: django-autoscaling
spec:
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: django-app
   minReplicas: 1
   maxReplicas: 5
   targetCPUUtilizationPercentage: 70

