apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
  DJANGO_SECRET_KEY: KmErIyhncjIzYzhxM21zdyNpYzFqMHozZCtpaXhuX3J4NGl2JnpwM194Jnp3dS1nCg==
  db_passwd: Q29uZHVpdDEyMzQK
  db_user: Y29uZHVpdAo=
  db_name: Y29uZHVpdF9kYgo=
