version: '3.7'
services:
  db:
    image: postgres:14.6
    container_name: postgres1
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 45s
      retries: 10
    networks:
      - conduit

  conduit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conduit
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - conduit

volumes:
  pgdata:
    
networks:
  conduit:
    driver: bridge
