apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduit-app-deployment
  labels:
    app: conduit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conduit-app
  template:
    metadata:
      labels:
        app: conduit-app
    spec:
      containers:
      - name: postgres
        image: achebeh/conduit-app:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
        env:
        - name: DJANGO_SECRET_KEY
          value: $(DJANGO_SECRET_KEY)
        - name: DB_NAME
          value: $(DB_NAME)
        - name: DB_USER
          value: $(DB_USER)
        - name: DB_PASS
          value: $(t
          )
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DB_HOST
          value: postgres-service
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: conduit-service
spec:
  type: LoadBalancer
  selector:
    app: conduit-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000